export const SET_LOGGED_USER = 'SET_LOGGED_USER';
export const NULL_LOGIN_ERROR = 'NULL_LOGIN_ERROR';
export const LOG_OUT = 'LOG_OUT';
export const SET_SOCKET = 'SET_SOCKET';
export const RAISE_LOGIN_ERROR = 'RAISE_LOGIN_ERROR';
export const SET_ADMIN_CURRENT_GROUP_ID = 'SET_ADMIN_CURRENT_GROUP_ID';
export const SET_ADMIN_NAV_TREE = 'SET_ADMIN_NAV_TREE'
export const SET_NAV_TREE = 'SET_NAV_TREE';
export const SET_MESSAGES = 'SET_MESSAGES'
export const SWITCH_DIALOGUE = 'SWITCH_DIALOGUE';

